openapi: 3.0.0
info:
  title: Auction API
  version: 1.0.0
paths:
  /auctions/{auction_id}/bids:
    get:
      summary: Получение ставок по аукциону
      parameters:
        - name: auction_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    bind_id:
                      type: integer
                    item_id:
                      type: integer
                    buyer_id:
                      type: integer
                    amount:
                      type: number
                    timestamp:
                      type: string
                example:
                  - bind_id: 1
                    item_id: 1
                    buyer_id: 4
                    amount: 150
                    timestamp: "2023-03-19T15:30:00Z"
                  - bind_id: 2
                    item_id: 1
                    buyer_id: 5
                    amount: 175
                    timestamp: "2023-03-19T15:35:00Z"
                  - bind_id: 3
                    item_id: 1
                    buyer_id: 6
                    amount: 200
                    timestamp: "2023-03-19T15:40:00Z"
  /auth/registration:
    post:
      summary: Регистрация нового пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                fullname:
                  type: string
                email:
                  type: string
                role:
                  type: string
                icon:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  username:
                    type: string
                  fullname:
                    type: string
                  email:
                    type: string
                  role:
                    type: string
                  icon:
                    type: string
                  Message:
                    type: string                    
              example:
                id: "123"
                username: "user123"
                fullname: "Иванов Иван Иванович"
                email: "user123@example.ru"
                role: "buyer"
                icon: "onlineauction.ru/content/images/ico112233.png"
                Message: "Пользователь создан"
  /auctions/{auction_id}/binds/{bind_id}:
    delete:
      summary: Отмена ставки по аукциону
      parameters:
        - name: auction_id
          in: path
          required: true
          schema:
            type: string
        - name: bind_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  auction_id:
                    type: string
                  binds_id:
                    type: string
                  Message:
                    type: string
              example:
                auction_id: "123"
                binds_id: "321"
                Message: "Ставка отменена" 
  /sellers/{seller_id}/orders/{order_id}:
    patch:
      summary: Update order status for a seller
      parameters:
        - name: seller_id
          in: path
          required: true
          schema:
            type: string
        - name: order_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                tracking_number:
                  type: string
                timestamp:
                  type: string
                  format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: string
                  status:
                    type: string
                  tracking_number:
                    type: string
                  timestamp:
                    type: string
                    format: date-time
              example:
                order_id: "321"
                status: "Принят покупателем"
                tracking_number: "1234-5678-9876-5432"
                timestamp: "2023-03-19T15:30:00Z"
  /sellers/{seller_id}/subscriptions/{subscription_id}:
    put:
      summary: Update seller's subscription plan
      parameters:
        - name: seller_id
          in: path
          required: true
          schema:
            type: string
        - name: subscription_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                plan_id:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  subscription_id:
                    type: string
                  new_plan:
                    type: string
                  Message:
                    type: string
              example:
                subscription_id: "321"
                new_plan: "plan123"
                Message: "Тарифный план изменен"                                               
