apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: sberuniversity-online-dr
spec:
  host: sberuniversity.online
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 80
        tls:
          mode: SIMPLE